# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170331_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date',
            new_name='date_sub',
        ),
    ]
